name: Setup Expo React Native Project

on:
  workflow_dispatch: # Trigger manually from GitHub
  push:
    branches:
      - main

jobs:
  setup-expo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Step 4: Create a new Expo project
      - name: Create Expo Project
        run: |
          npx expo init my-react-native-app --template blank
          cd my-react-native-app
          echo "Project successfully created"

      # Step 5: Commit generated project to the repo
      - name: Commit Expo Project
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Initialize Expo React Native Project"
        continue-on-error: true
      # Step 3: Install dependencies
      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Step 4: Create a new Expo project
      - name: Create Expo Project
        run: |
          npx expo init my-react-native-app --template blank
          cd my-react-native-app
          echo "Project successfully created"

      # Step 5: Commit generated project to the repo
      - name: Commit Expo Project
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Initialize Expo React Native Project"
        continue-on-error: true
