name: Setup Expo React Native Project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-expo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean up existing directory (optional)
        run: |
          if [ -d "my-react-native-app" ]; then
            rm -rf my-react-native-app
          fi

      - name: Create Expo Project
        run: |
          npx create-expo-app my-react-native-app --template blank --force
          cd my-react-native-app
          echo "Project successfully created"
